site_name: EmuDeck Developer Docs
site_url: https://docs.emudeck.com
repo_url: https://github.com/EmuDeck

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Project Structure:
      - configs/: configs.md
      - core/: core.md
      - tools/: tools.md
      - functions/:
          - helpers.py: helpers.md
          - emus_scripts/: emus-scripts.md
          - tools_scripts/: tools-scripts.md
          - Other files: functions.md
  - Root Files:
      - api.py: api.md
      - setup.py: setup.md
      - versions.json: versions.md
